name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    env:
      OPENRESTY_PREFIX: "/usr/local/openresty"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Get dependencies
        run: sudo apt install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl luarocks

      - name: Before install
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          git clone https://github.com/openresty/test-nginx.git test-nginx
          docker-compose --project-directory . -f t/docker-compose.yml up -d

      - name: Install
        run: |
          wget https://raw.githubusercontent.com/api7/apisix-build-tools/master/build-apisix-base.sh
          chmod +x build-apisix-base.sh
          OR_PREFIX=$OPENRESTY_PREFIX CC="clang -fsanitize=address -fcolor-diagnostics -Qunused-arguments" \
            cc_opt="-Werror" \
            ./build-apisix-base.sh latest
          sudo luarocks make ./grpc-client-nginx-module-dev-0-0.rockspec
          cd ./grpc-engine && go build -o libgrpc_engine.so -buildmode=c-shared main.go

      - name: Script
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          export GODEBUG=x509sha1=1
          prove -I. -Itest-nginx/lib -r t/
